services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8000:8000"
    entrypoint: /code/entrypoint.sh
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:17
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 7
      start_period: 3s
      timeout: 5s
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      start_period: 3s
      timeout: 3s
    volumes:
      - redis-data:/data

  event-consumer:
    build:
      dockerfile: Dockerfile
      context: ./backend
    env_file: ".env"
    entrypoint: ["uv", "run", "python", "-m", "src.notifications.consumer"]
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  celery-worker:
    build:
      dockerfile: Dockerfile
      context: ./backend
    env_file: ".env"
    command: uv run celery -A src.core.celery worker --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_UI_BIND_ADDR: 0.0.0.0:8025
      MP_SMTP_BIND_ADDR: 0.0.0.0:1025

  pgadmin:
    image: dpage/pgadmin4
    env_file: ".env"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data-prod:/var/lib/pgadmin

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    entrypoint: /code/entrypoint.sh
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres-data-prod:
  pgadmin-data-prod:
  redis-data: