services:
  devcontainer:
    image: "mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04"
    env_file: .env
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ../:/workspaces/family-task-hub:cached
    command: sleep infinity
    networks:
      - default

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 7
      start_period: 3s
      timeout: 5s
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    image: "mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04"
    env_file: .env
    working_dir: /workspaces/family-task-hub/backend
    volumes:
      - ../:/workspaces/family-task-hub:cached
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - default
    command: bash -c "curl -LsSf https://astral.sh/uv/install.sh | sh && /root/.local/bin/uv sync && /root/.local/bin/uv run celery -A src.tasks.email_sender worker --loglevel=info"
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "15432:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data-dev:/var/lib/pgadmin
    networks:
      - default

volumes:
  postgres-data-dev:
  pgadmin-data-dev:
  redis_data:

networks:
  default:
    driver: bridge