"""add image_url to user

Revision ID: 19b255b59aed
Revises: d73289e99e19
Create Date: 2026-02-01 14:43:25.404599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '19b255b59aed'
down_revision: Union[str, Sequence[str], None] = 'd73289e99e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_url')
    # ### end Alembic commands ###
