"""Add clerk_id to users

Revision ID: d73289e99e19
Revises: 78c05d3c3a4f
Create Date: 2026-01-26 20:48:53.641096

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d73289e99e19"
down_revision: Union[str, Sequence[str], None] = "78c05d3c3a4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("task", "due_date", existing_type=sa.DATE(), nullable=False)
    op.add_column(
        "user",
        sa.Column(
            "clerk_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )

    # MANUAL STEP!
    # mark old users with clerk_id=OLD_USER_<ID>
    op.execute("""
        UPDATE "user"
        SET clerk_id = 'OLD_USER_' || CAST(id AS TEXT)
        WHERE clerk_id IS NULL
    """)
    op.alter_column("user", "clerk_id", nullable=False)

    op.create_index(op.f("ix_user_clerk_id"), "user", ["clerk_id"], unique=True)
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("hashed_password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_user_clerk_id"), table_name="user")
    op.drop_column("user", "clerk_id")
    op.alter_column("task", "due_date", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###
